version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./html:/var/www/html
    links:
      - php

  php:
    image: php:7.4-fpm
    volumes:
      - ./html:/var/www/html
    links:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: 'mysql'
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
